# Generated by Django 5.2.7 on 2025-11-05 11:19

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import recipe.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('profile_picture', models.ImageField(blank=True, default='default.png', null=True, upload_to=recipe.models.user_profile_upload_to)),
                ('bio', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('category', models.PositiveIntegerField(choices=[(0, 'Veg'), (1, 'Vegan'), (2, 'Non-Veg')], db_index=True, default=0)),
                ('cuisine', models.CharField(db_index=True, max_length=50)),
                ('difficulty', models.PositiveIntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], db_index=True, default=0)),
                ('servings', models.PositiveIntegerField(default=1, help_text='Number of people the recipe serves')),
                ('prep_time', models.PositiveIntegerField(help_text='Time required to prepare ingredients in minutes')),
                ('total_time', models.PositiveIntegerField(help_text='Preparation time + Cooking Time in minutes', validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(5)])),
                ('instructions', models.TextField()),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recipes',
                'ordering': ('-created', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(help_text='Estimated calories per serving')),
                ('protein', models.PositiveIntegerField(help_text='Estimated protein per serving')),
                ('fat', models.PositiveIntegerField(help_text='Estimated fat per serving')),
                ('sugar', models.PositiveIntegerField(help_text='Estimated sugar per serving')),
                ('fiber', models.PositiveIntegerField(help_text='Estimated fiber per serving')),
                ('carbohydrates', models.PositiveIntegerField(help_text='Estimated carbohydrates per serving')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='recipe.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.IntegerField(choices=[(0, 'grams'), (1, 'kilogram'), (2, 'teaspoon'), (3, 'tablespoon'), (4, 'cup'), (5, 'piece')], default=0)),
                ('optional', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipe.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(blank=True, default='default-recipe.jpg', null=True, upload_to=recipe.models.recipe_image_upload_to)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recipe.recipe')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_like', to='recipe.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'recipe')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_recipes', through='recipe.RecipeLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('recipes', models.ManyToManyField(blank=True, to='recipe.recipe')),
            ],
            options={
                'ordering': ('-created', 'title'),
                'unique_together': {('title', 'owner')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('title', 'author')},
        ),
    ]
