# Generated by Django 5.2.9 on 2025-12-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipelike_alter_collection_options_and_more'),
        ('recipe', '0002_remove_recipe_likes_user_alter_recipe_likes_and_more'),
    ]

    operations = [
    ]
